[package]
name = "demo_pyo3_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "demo_pyo3_extension"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
